#!/usr/bin/env bash
#
# Builds the self-contained agent bundle (agent.zip): a relocatable standalone
# CPython + the locked dependency set + the api SDK. Build-time tool, runs in CI
# only. Host platform only; cross-build extension point is marked below.

set -euo pipefail

if [[ -t 1 ]]; then
  C_STEP=$'\033[1;36m'; C_OK=$'\033[1;32m'; C_ERR=$'\033[1;31m'
  C_PKG=$'\033[1;33m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_STEP=''; C_OK=''; C_ERR=''; C_PKG=''; C_DIM=''; C_OFF=''
fi
step() { printf '%s▶ %s%s\n' "$C_STEP" "$1" "$C_OFF"; }
info() { printf '%s    %s%s\n' "$C_DIM" "$1" "$C_OFF"; }
pkg()  { printf '%s    • %s%s\n' "$C_PKG" "$1" "$C_OFF"; }
ok()   { printf '%s✓ %s%s\n' "$C_OK" "$1" "$C_OFF"; }
die()  { printf '%s✗ %s%s\n' "$C_ERR" "$1" "$C_OFF" >&2; exit 1; }

AGENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$AGENT_DIR"

PY_VERSION="$(tr -d '[:space:]' < .python-version)"
PY_MINOR="${PY_VERSION%.*}"

case "$(uname -s)-$(uname -m)" in
  Linux-x86_64)   PLATFORM_LABEL="linux-x86_64" ;;
  Linux-aarch64)  PLATFORM_LABEL="linux-aarch64" ;;
  Darwin-arm64)   PLATFORM_LABEL="macos-aarch64" ;;
  Darwin-x86_64)  PLATFORM_LABEL="macos-x86_64" ;;
  *)              PLATFORM_LABEL="$(uname -s)-$(uname -m)" ;;
esac

BUILD_DIR="$AGENT_DIR/build"
STAGE_DIR="$BUILD_DIR/.python-stage"
BUNDLE_DIR="$BUILD_DIR/$PLATFORM_LABEL"
ZIP_PATH="$BUILD_DIR/agent-$PLATFORM_LABEL.zip"
REQ_LOCK="$AGENT_DIR/requirements.lock"

step "Building agent bundle"
info "platform : $PLATFORM_LABEL"
info "python   : CPython $PY_VERSION"
info "output   : $BUNDLE_DIR"
rm -rf "$BUNDLE_DIR" "$STAGE_DIR"
mkdir -p "$BUNDLE_DIR" "$STAGE_DIR"

# Freeze uv.lock -> pip-consumable requirements.lock (redirect, not -o, so the
# autogenerated header records a portable command with no absolute path).
step "Freezing locked dependencies"
uv export --no-dev --no-emit-project --format requirements-txt > "$REQ_LOCK"
while IFS= read -r line; do pkg "$line"; done < <(grep -oE '^[A-Za-z0-9._-]+==[^ ]+' "$REQ_LOCK")

# Relocatable standalone CPython (python-build-standalone "install_only").
step "Installing standalone CPython $PY_VERSION"
uv python install --install-dir "$STAGE_DIR" "$PY_VERSION" >/dev/null
# Keep the real cpython dir, drop uv's minor-version symlink beside it.
shopt -s nullglob
CPYTHON_DIRS=()
for d in "$STAGE_DIR"/cpython-*; do
  [[ -d "$d" && ! -L "$d" ]] && CPYTHON_DIRS+=("$d")
done
shopt -u nullglob
[[ ${#CPYTHON_DIRS[@]} -eq 1 ]] || die "expected one cpython-* dir, found ${#CPYTHON_DIRS[@]}"
mv "${CPYTHON_DIRS[0]}" "$BUNDLE_DIR/python"
rm -rf "$STAGE_DIR"
PY_BIN="$BUNDLE_DIR/python/bin/python3.11"

# Install deps into a plain dir on PYTHONPATH (not a venv).
#   --only-binary :all:  wheels only (required for cross-build)
#   --link-mode=copy     no hardlinks into uv's cache; bundle is self-contained
#   --python-version     pins the wheel ABI to the bundled interpreter
step "Installing dependencies into libs/"
uv pip install \
  --target "$BUNDLE_DIR/libs" \
  --python-version "$PY_MINOR" \
  --link-mode=copy \
  --only-binary :all: \
  -r "$REQ_LOCK" \
  --quiet
ok "dependencies installed"
# Cross-build: add --python-platform <triple> here and source python/ from
# python-build-standalone for the target.

step "Vendoring api SDK"
cp -r "$AGENT_DIR/src/api" "$BUNDLE_DIR/libs/api"
pkg "api"

if [[ -f "$AGENT_DIR/runner.py" ]]; then
  cp "$AGENT_DIR/runner.py" "$BUNDLE_DIR/runner.py"
  pkg "runner.py"
fi
if [[ -f "$AGENT_DIR/agent.sample.py" ]]; then
  cp "$AGENT_DIR/agent.sample.py" "$BUNDLE_DIR/agent.py"
  pkg "agent.py"
fi

step "Zipping bundle"
rm -f "$ZIP_PATH"
( cd "$BUNDLE_DIR" && zip -rq "$ZIP_PATH" . )

ok "done"
info "bundle : $BUNDLE_DIR"
info "zip    : $ZIP_PATH"
printf '\n%sacceptance test:%s\n' "$C_STEP" "$C_OFF"
printf "  PYTHONPATH='%s/libs' '%s' -s -c \"import websockets, api; print('OK', websockets.__version__)\"\n" \
  "$BUNDLE_DIR" "$PY_BIN"
