#!/usr/bin/env bash
#
# Builds the self-contained agent bundle (agent.zip): a relocatable standalone
# CPython + the locked dependency set + the api SDK. Build-time tool, runs in CI
# only. Host platform only; cross-build extension point is marked below.

set -euo pipefail

if [[ -t 1 ]]; then
  C_STEP=$'\033[1;36m'; C_OK=$'\033[1;32m'; C_ERR=$'\033[1;31m'
  C_PKG=$'\033[1;33m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_STEP=''; C_OK=''; C_ERR=''; C_PKG=''; C_DIM=''; C_OFF=''
fi
step() { printf '%s▶ %s%s\n' "$C_STEP" "$1" "$C_OFF"; }
info() { printf '%s    %s%s\n' "$C_DIM" "$1" "$C_OFF"; }
pkg()  { printf '%s    • %s%s\n' "$C_PKG" "$1" "$C_OFF"; }
ok()   { printf '%s✓ %s%s\n' "$C_OK" "$1" "$C_OFF"; }
die()  { printf '%s✗ %s%s\n' "$C_ERR" "$1" "$C_OFF" >&2; exit 1; }

AGENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$AGENT_DIR"

PY_VERSION="$(tr -d '[:space:]' < .python-version)"
PY_MINOR="${PY_VERSION%.*}"

# Label: `agent-<label>.zip`
#   label           game asset suffix   bundle python
#   linux-x86_64    linux.x86_64        python/bin/python3.11
#   windows-x86_64  windows.exe         python/python.exe
#   macos-aarch64   macos.zip           python/bin/python3.11
#   macos-x86_64    macos.zip           python/bin/python3.11
case "$(uname -s)-$(uname -m)" in
  Linux-x86_64)                              PLATFORM_LABEL="linux-x86_64" ;;
  Linux-aarch64)                             PLATFORM_LABEL="linux-aarch64" ;;
  Darwin-arm64)                              PLATFORM_LABEL="macos-aarch64" ;;
  Darwin-x86_64)                             PLATFORM_LABEL="macos-x86_64" ;;
  MINGW*-x86_64|MSYS*-x86_64|CYGWIN*-x86_64) PLATFORM_LABEL="windows-x86_64" ;;
  *) die "unsupported build host: $(uname -s)-$(uname -m)" ;;
esac

BUILD_DIR="$AGENT_DIR/build"
PY_CACHE_DIR="$BUILD_DIR/.python-cache"
BUNDLE_DIR="$BUILD_DIR/$PLATFORM_LABEL"
ZIP_PATH="$BUILD_DIR/agent-$PLATFORM_LABEL.zip"
REQ_LOCK="$AGENT_DIR/requirements.lock"

step "Building agent bundle"
info "platform : $PLATFORM_LABEL"
info "python   : CPython $PY_VERSION"
info "output   : $BUNDLE_DIR"
rm -rf "$BUNDLE_DIR"
mkdir -p "$BUNDLE_DIR"

# Freeze uv.lock -> pip-consumable requirements.lock (redirect, not -o, so the
# autogenerated header records a portable command with no absolute path).
step "Freezing locked dependencies"
uv export --no-dev --no-emit-project --format requirements-txt > "$REQ_LOCK"
while IFS= read -r line; do pkg "$line"; done < <(grep -oE '^[A-Za-z0-9._-]+==[^ ]+' "$REQ_LOCK")

# Relocatable standalone CPython (python-build-standalone "install_only").
# The cache dir persists across builds; uv skips the download when the version
# is already installed there, so only the first build hits the network.
step "Installing standalone CPython $PY_VERSION"
mkdir -p "$PY_CACHE_DIR"
uv python install --install-dir "$PY_CACHE_DIR" "$PY_VERSION" >/dev/null
# Copy the real cpython dir, ignoring uv's minor-version symlink beside it.
shopt -s nullglob
CPYTHON_DIRS=()
for d in "$PY_CACHE_DIR"/cpython-"$PY_VERSION"-*; do
  [[ -d "$d" && ! -L "$d" ]] && CPYTHON_DIRS+=("$d")
done
shopt -u nullglob
[[ ${#CPYTHON_DIRS[@]} -eq 1 ]] || die "expected one cpython-$PY_VERSION-* dir in $PY_CACHE_DIR, found ${#CPYTHON_DIRS[@]}"
cp -a "${CPYTHON_DIRS[0]}" "$BUNDLE_DIR/python"
if [[ "$PLATFORM_LABEL" == windows-* ]]; then
  PY_BIN="$BUNDLE_DIR/python/python.exe"
else
  PY_BIN="$BUNDLE_DIR/python/bin/python$PY_MINOR"
fi

# Install deps into a plain dir on PYTHONPATH (not a venv).
#   --only-binary :all:  wheels only (required for cross-build)
#   --link-mode=copy     no hardlinks into uv's cache; bundle is self-contained
#   --python-version     pins the wheel ABI to the bundled interpreter
step "Installing dependencies into libs/"
uv pip install \
  --target "$BUNDLE_DIR/libs" \
  --python-version "$PY_MINOR" \
  --link-mode=copy \
  --only-binary :all: \
  -r "$REQ_LOCK" \
  --quiet
ok "dependencies installed"
# Cross-build: add --python-platform <triple> here and source python/ from
# python-build-standalone for the target.

step "Vendoring api SDK"
cp -r "$AGENT_DIR/src/api" "$BUNDLE_DIR/libs/api"
pkg "api"

if [[ -f "$AGENT_DIR/runner.py" ]]; then
  cp "$AGENT_DIR/runner.py" "$BUNDLE_DIR/runner.py"
  pkg "runner.py"
fi
# Ship the working agent.py as the default; fall back to the sample if absent.
if [[ -f "$AGENT_DIR/agent.py" ]]; then
  cp "$AGENT_DIR/agent.py" "$BUNDLE_DIR/agent.py"
  pkg "agent.py"
fi

step "Verifying bundle"
PYTHONPATH="$BUNDLE_DIR/libs" "$PY_BIN" -s -c 'import websockets, api' \
  || die "bundle verification failed: import websockets, api"
ok "import websockets, api"

step "Zipping bundle"
rm -f "$ZIP_PATH"
if command -v zip >/dev/null 2>&1; then
  ( cd "$BUNDLE_DIR" && zip -rq "$ZIP_PATH" . )
else
  # Windows CI runners have no zip(1); the bundled interpreter fills in.
  # zipfile stores no unix permissions, so this branch is windows-only.
  ( cd "$BUNDLE_DIR" && "$PY_BIN" -m zipfile -c "$ZIP_PATH" * )
fi

ok "done"
info "bundle : $BUNDLE_DIR"
info "zip    : $ZIP_PATH"
